/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/3d/avatar.glb 
*/


import React, { useEffect, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

import avatarScene from '../assets/3d/avatar.glb'

const Avatar = ({currentAnimation, ...props}) => {  
  const group = useRef()
  const { scene, animations } = useGLTF(avatarScene)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(()=> {
    Object.values(actions).forEach((action)=>action.stop());
    if(actions[currentAnimation]){
      actions[currentAnimation].play();
    }
  },[actions, currentAnimation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Hips} />
          <skinnedMesh name="avaturn_body" geometry={nodes.avaturn_body.geometry} material={materials.avaturn_body_material} skeleton={nodes.avaturn_body.skeleton} />
          <skinnedMesh name="avaturn_glasses_0" geometry={nodes.avaturn_glasses_0.geometry} material={materials.avaturn_glasses_0_material} skeleton={nodes.avaturn_glasses_0.skeleton} />
          <skinnedMesh name="avaturn_glasses_1" geometry={nodes.avaturn_glasses_1.geometry} material={materials.avaturn_glasses_1_material} skeleton={nodes.avaturn_glasses_1.skeleton} />
          <skinnedMesh name="avaturn_hair_0" geometry={nodes.avaturn_hair_0.geometry} material={materials.avaturn_hair_0_material} skeleton={nodes.avaturn_hair_0.skeleton} />
          <skinnedMesh name="avaturn_look_0" geometry={nodes.avaturn_look_0.geometry} material={materials.avaturn_look_0_material} skeleton={nodes.avaturn_look_0.skeleton} />
          <skinnedMesh name="avaturn_look_1" geometry={nodes.avaturn_look_1.geometry} material={materials.avaturn_look_1_material} skeleton={nodes.avaturn_look_1.skeleton} />
          <skinnedMesh name="avaturn_shoes_0" geometry={nodes.avaturn_shoes_0.geometry} material={materials.avaturn_shoes_0_material} skeleton={nodes.avaturn_shoes_0.skeleton} />
        </group>
        <group name="sitting" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.Hips_3} />
        </group>
        <group name="writing" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.Hips_4} />
        </group>
        <group name="disbelief" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.Hips_2} />
        </group>
        <group name="cheering" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.Hips_1} />
        </group>
      </group>
    </group>
  )
}

export default Avatar
