/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/3d/bird.glb 
Author: Assets_Animated (https://sketchfab.com/Assets_Animated)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robin--bird-ec1c6e2250824c3987cde64ea29ccd52
Title: Robin_ Bird
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

import birdScene from '../assets/3d/bird.glb'

const Bird =  ({isRotating, ...props}) => {
  const group = React.useRef()
  const { scene, animations } = useGLTF(birdScene)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (isRotating) {
      actions["Robin_Bird_Fly"].play();
    } else {
      actions["Robin_Bird_Fly"].stop();
    }
  }, [actions, isRotating]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[1.624, 0, 0]}>
          <group name="53e90c232fbf4a3da570da91a86bd7e5fbx" rotation={[-Math.PI, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" />
                  <group name="Robin_Bird" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Robin_Bird_Merge} skeleton={nodes.Object_7.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Bird
