/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/3d/exclamation.glb 
Author: HyperProduct (https://sketchfab.com/hyperproduct)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/exclamation-point-8161d30cfabe446dae1fabfb920b0f58
Title: Exclamation Point
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import exclamationMark from '../assets/3d/exclamation.glb'

const Exclamation = ({...props}) => {
  const { nodes, materials } = useGLTF(exclamationMark)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[0, 5.917, 0]} scale={[0.5, 1.5, 0.4]} />
    </group>
  )
}

export default Exclamation