/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/3d/parrot.glb 
Author: sacha.lujan33 (https://sketchfab.com/sacha.lujan33)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/parrot-ai-07c345ea9ee941e391e4990072bc1853
Title: Parrot ai
*/

import React, {useRef, useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import parrotScene from '../assets/3d/parrot.glb'

const Parrot =  ({isRotating, ...props}) => {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF(parrotScene)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (isRotating) {
      actions["Object_0"].play();
    } else {
      actions["Object_0"].play();
    }
  }, [actions, isRotating]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_5" position={[0, -7.077, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.08}>
                <group name="ba8148bfaddd4c8bafc9e56aaab5ef7dabccleanermaterialmergergle_4">
                  <group name="Object_2_3" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_3_2">
                      <group name="MorphMainGroup_1">
                        <group name="U3DMeshShape_0">
                          <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={materials.U3DMeshShape} morphTargetDictionary={nodes.mesh_0.morphTargetDictionary} morphTargetInfluences={nodes.mesh_0.morphTargetInfluences} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Parrot
